# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a631a6da7ef584ebe697aa63275eeaf35ff8e3108b4929890e7540cf5420c1d05abd27a9671ea1d11da5b59330ec984c44736ee5ca32a269985997eac3daa9dd

test:
  secret_key_base: 4866e1c87565235f64d562ebe6c8fc919c77e420a73990f66e134139c2cd706b6ab87818cc2dd6d2fad4d8d4305c8f01ab9036db2678af5be51f138f9d375bfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
